# Generated by Django 4.0.4 on 2022-04-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_remove_post_created_at_remove_post_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
