# Generated by Django 4.0.4 on 2022-04-20 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_topic_starter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='board',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='boards.board'),
        ),
    ]
