# Generated by Django 4.0.4 on 2022-04-20 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_alter_topic_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
